# Generated by Django 3.2.4 on 2021-06-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='first_name',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
